version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:8.4.0
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
volumes:
  mysql:
    name: mysql
